# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, Actions ]
  pull_request:
    branches: [ master, Actions ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        os: [windows, ubuntu, macos]
    
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download SteamWorks SDK
        uses: actions/checkout@v4
        with:
          repository: flibitijibibo/steamworks-sdk
          ref: 1.61
          path: SteamSDK

      - name: Setup AIR SDK
        uses: joshtynjala/setup-adobe-air-action@v2
        with:
          air-version: 51.1
          accept-license: true

      - name: Add msbuild to PATH # MSBuild is needed to build Visual Studio Projects on the CLI
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@v2
        
      - name: Build (Windows)
        if: runner.os == 'Windows'
        run: |
          mkdir SteamSDK\public
          xcopy SteamSDK\steam SteamSDK\public
          set "AIR_SDK=%AIR_HOME%"
          set "FLEX_SDK=%AIR_HOME%"
          set "STEAM_SDK=%GITHUB_WORKSPACE%\SteamSDK"
          msbuild src/FRESteamWorks.csproj /p:Platform=x64 /p:Configuration=Release
          msbuild src/FRESteamWorks.csproj /p:Platform=Win32 /p:Configuration=Release
          cd lib/bin
          xcopy ..\..\src\Release\FRESteamWorks.dll .
          xcopy ..\..\src\Release\FRESteamWorks-64.dll .
          mkdir FRESteamWorks.framework
          echo "" >> FRESteamWorks.framework/FRESteamWorks
          echo "" >> FRESteamWorks.so
          acompc +configname=air -source-path ..\src ^
                             -debug=false -optimize ^
                             -include-sources ..\src\ ^
                             -swf-version=11 -output FRESteamWorksLib.swc
          7z x FRESteamWorksLib.swc
          adt -package -target ane FRESteamWorks.ane descriptor.xml ^
                         -swc FRESteamWorksLib.swc ^
                         -platform Windows-x86 library.swf FRESteamWorks.dll ^
                         -platform Windows-x86-64 library.swf FRESteamWorks-64.dll ^
                         -platform MacOS-x86-64 library.swf FRESteamWorks.framework ^
                         -platform Linux-x86-64 library.swf FRESteamWorks.so ^
                         -platform default library.swf

      - name: Build (Linux)
        if: runner.os == 'Linux'
        run: |
          mkdir SteamSDK/public
          cp -r SteamSDK/steam SteamSDK/public
          export AIR_SDK=$AIR_HOME
          export FLEX_SDK=$AIR_HOME
          export STEAM_SDK=$GITHUB_WORKSPACE/SteamSDK
          
          cd src
          make -j${nproc}
          cd ../lib/bin
          cp ../../src/FRESteamWorks/FRESteamWorks.so .
          acompc +configname=air -source-path ../src \
                               -debug=false -optimize \
                               -include-sources ../src/ \
                               -swf-version=11 -output FRESteamWorksLib.swc
                    
          7z x FRESteamWorksLib.swc
          touch FRESteamWorks-64.dll
          touch FRESteamWorks.dll
          mkdir FRESteamWorks.framework
          touch FRESteamWorks.framework/FRESteamWorks
          adt -package -target ane FRESteamWorks.ane descriptor.xml \
                             -swc FRESteamWorksLib.swc \
                             -platform Windows-x86 library.swf FRESteamWorks.dll \
                             -platform Windows-x86-64 library.swf FRESteamWorks-64.dll \
                             -platform MacOS-x86-64 library.swf FRESteamWorks.framework \
                             -platform Linux-x86-64 library.swf FRESteamWorks.so \
                             -platform default library.swf
      
      - name: Build (macOS)
        if: runner.os == 'macOS'
        run: |
          mkdir SteamSDK/public
          cp -r SteamSDK/steam SteamSDK/public
          export AIR_SDK=$AIR_HOME
          export FLEX_SDK=$AIR_HOME
          export STEAM_SDK=$GITHUB_WORKSPACE/SteamSDK
          
          touch build/bin/FRESteamworks-64.dll
          touch build/bin/FRESteamworks.dll
          touch build/bin/FRESteamworks.so
          cd src
          xcodebuild -project FRESteamWorks.xcodeproj

      - uses: actions/upload-artifact@v4
        with:
          name: FRESteamWorks-${{runner.os}}
          path: lib/bin/FRESteamWorks.ane
          
          
